server:
  port: 8080
  servlet:
    context-path: /api

swagger:
  title: @project.name@
  description: @project.description@
  version: @project.version@

hibernate:
  hbm2ddl:
    auto: none
  dialect: org.hibernate.dialect.PostgreSQLDialect

postgres:
  driver-class-name: org.postgresql.Driver
  url: ${SPRING_DATABASE_URL}
  username: ${SPRING_DATABASE_USERNAME}
  password: ${SPRING_DATABASE_PASSWORD}

spring:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml